### ISSUE TITLE
How to get the dataset?

### ISSUE THREAD

**Issue by cumtwb** [kracwarlock/action-recognition-visual-attention#15]
How did you require the dataset? just like train_features.h5, train_framenum.txt and train_labels.txt, etc.
`self.data_file       = '/ais/gobi3/u/shikhar/ucf11/dataset/train_features.h5'
      self.num_frames_file = '/ais/gobi3/u/shikhar/ucf11/dataset/train_framenum.txt'
      self.labels_file     = '/ais/gobi3/u/shikhar/ucf11/dataset/train_labels.txt'
      self.vid_name_file   = '/ais/gobi3/u/shikhar/ucf11/dataset/train_filename.txt'
      self.dataset_name    = 'features'`
I don't know how to get these? Download from web or generate these yourself? Could you tell me the method. Thanks.

**Comment by kracwarlock** [comment]
The file format for these is provided at https://github.com/kracwarlock/action-recognition-visual-attention/blob/master/util/README.md

I uploaded some of these scripts in #2, #6 and #1 
Let me know if there is any other issue

**Comment by ozgemercanoglu** [comment]
Dear @kracwarlock, could you please share train_filename.txt, train_labels.txt, train_framenum.txt and train_features.h5 for HMDB-51 dataset?
