### ISSUE TITLE
Python Scripts for CNN Encoding Generation

### ISSUE THREAD

**Issue by 345ishaan** [kracwarlock/action-recognition-visual-attention#19]
Hi, 

I am using tensorflow in python to generate CNN encodings for the video sequences provided by UCF101 dataset. I am dumping the outputs sequentially in a HDF5 file. My code is currently taking 20s per video file to store it's data in HDF5 file. So, for 9500 videos sequences, it will take a lot of time.

Can someone share their experience in it?

**Comment by YinRui1991** [comment]
The author used UCF11 in his paper. UCF11 and UCF101 are two different datasets. UCF101 is much bigger than UCF11.
