### ISSUE TITLE
Can anyone share the code mentioned in the closed issue #6 which is used to combine features to h5 format?

### ISSUE THREAD

**Issue by YinRui1991** [kracwarlock/action-recognition-visual-attention#20]
I am interested in combination of deep learning and attention mechanism. I think this is a good way to know what deep learning focus on. I have got the features extracted by convolution layer of GoogLeNet, but the second link in issue #6 is not available (To combine the individual files generated by this script that he sent me I used https://gist.github.com/kracwarlock/96499936487d6125dd010319669c6648). 
  Can anyone share this code again? 
  Thanks very much!

**Comment by GerardoHH** [comment]
Hi @YinRui1991 
Sorry but long time I stopped working on this project, and I already lost the code you tell me, but the link you mentioned is working.

Hope you solve the problem.

**Comment by YinRui1991** [comment]
Thanks for your reply. I can't open the link because it is blocked by the government. I asked my friend in America to send the code. Benefiting from the discussion in #1, #2 and #6 questions, I have replicated the experiments. 
Thanks again!

**Comment by vicely07** [comment]
@YinRui1991 Can you send me the code? I have problem creating the file in issue #6
